// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_clean_architecture/test/data/provider/network/apis/receipt_api_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:flutter_clean_architecture/data/provider/network/api.dart'
    as _i3;
import 'package:flutter_clean_architecture/data/provider/network/api_request_representation.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [APIProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAPIProvider extends _i1.Mock implements _i3.APIProvider {
  MockAPIProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get instance => (super.noSuchMethod(
        Invocation.getter(#instance),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#instance),
        ),
      ) as _i2.Dio);

  @override
  _i4.Future<_i2.Response<dynamic>> request(
          _i5.APIRequestRepresentable? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_1<dynamic>(
          this,
          Invocation.method(
            #request,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
}
